- art-gallery-medium-article-website/public/index.html
- art-gallery-medium-article-website/src/App.js
- art-gallery-medium-article-website/src/TokenContextProvider.js
- ecommerce-store-website/src/pages/_app.js
- hotel-bogota-active-negotiation-website/public/index.html
- hotel-bogota-active-negotiation-website/src/App.js
- hotel-bogota-active-negotiation-website/src/TokenContextProvider.js
- hotel-bogota-passive-negotiation-website/src/App.js
- ticket-issuer-url-website/src/App.js
- token-outlet-website/src/index.ts
- tokenConfig.json
- typescript-bare-bones-demo/src/index.html
- typescript-bare-bones-demo/src/index.ts
Fixes:
- Update client config to be compatible with new version
- Fix react race condition causing .overlay-tn to not be rendered before negotiator requires it. This was not a problem before since the HTTP requests for contract metadata would block the initialization of the UI.
> Fixes for v2

- ecommerce-store-website/src/base/nft-data-store.js
Ticket: https://smarttokenlabs.atlassian.net/browse/TKN-317
> feat: 🎸 Minor Text Improvement

- art-gallery-medium-article-website/src/TokenContextProvider.js
Fixed discount prices not showing on art-gallery example
> fix: discount price not showing on art-gallery example

- typescript-bare-bones-demo/src/index.ts
@nicktaras This replaces Rinkeby tokens in barebones example with Goerli versions
> Chore: remove rinkeby

- .github/workflows/token-outlet-website.yml
@nicktaras this should hopefully fix the bug with the current staging demo
> Chore: tn repo ci build for outlet

- .github/workflows/token-outlet-website.yml
(cherry picked from commit ceddabc35373107274617b8d380be227746745a4)
> chore: Update token-outlet CI to use GIT builds of TN

- hotel-bogota-passive-negotiation-website/src/App.js
Fix callback loop caused by react lifecycle issue
> Fix: passive callback loop

- hotel-bogota-active-negotiation-website/src/TokenContextProvider.js
- hotel-bogota-active-negotiation-website/src/components/BookingModal/index.js
- hotel-bogota-passive-negotiation-website/src/App.js
- hotel-bogota-passive-negotiation-website/src/BookingModal/index.js
- hotel-bogota-passive-negotiation-website/src/TokenCard/index.js
- hotel-bogota-passive-negotiation-website/src/TokenNotificationCard/index.js
You can force redirect mode by setting param redirectMode=always in the URL hash query
i.e.
http://localhost:3000/#redirectMode=always
> fix: hotel bogota examples to work with redirect mode

- environment.js
- hotel-bogota-active-negotiation-website/config-overrides.js
- hotel-bogota-passive-negotiation-website/config-overrides.js
- ticket-issuer-url-website/config-overrides.js
- token-outlet-website/webpack.config.js
- typescript-bare-bones-demo/package-lock.json
- typescript-bare-bones-demo/src/index.html
- typescript-bare-bones-demo/src/index.ts
- Remove node polyfills from examples.
- Fix environment.js using wrong outlet.
- Remove duplicate issuer config (bare-bones).
- Add redirectMode flag changes.
> Fix: dev server config

- angular-bare-bones-demo/src/app/issues.ts
- svelte-demo/src/components/BrandConnector.svelte
- typescript-bare-bones-demo/package-lock.json
- typescript-bare-bones-demo/src/index.ts
- vue-boilerplate/src/App.vue
- vue-vite-boilerplate/src/App.vue
Added ERC20 test tokens for bare-bones examples
> Added ERC20 test tokens

- .github/workflows/build-examples.yml
- .github/workflows/deploy-to-gh-pages.yml
- .github/workflows/ecommerce-store-website.yml
- .github/workflows/token-outlet-website.yml
It's not currently supported in top level of action yml
> fix: comment description

- ecommerce-store-website/src/base/utils/interact.js
- ecommerce-store-website/src/ui/components/minter/minter.js
- ecommerce-store-website/src/ui/components/minter/minter.module.scss
fix for task:
https://smarttokenlabs.atlassian.net/browse/TKS-760
> feat: 🎸 minting state of mint button

- .github/workflows/build-examples.yml
- sonar-project.properties
Details: https://smarttokenlabs.atlassian.net/browse/TKS-809
✅ Closes: https://smarttokenlabs.atlassian.net/browse/TKS-809
> ci: 🎡 add sonar cloud scan in CI

- hotel-bogota-passive-negotiation-website/package-lock.json
- hotel-bogota-passive-negotiation-website/src/App.js
- ticket-issuer-url-website/package-lock.json
- ticket-issuer-url-website/src/App.js
- token-outlet-website/package-lock.json
- token-outlet-website/src/index.ts
This PR fixes this bug on Safari https://smarttokenlabs.atlassian.net/browse/TKS-859
> FIX: Fixed issuer bug o MAC+safari

- ecommerce-store-website/README.md
- ecommerce-store-website/next.config.js
- ecommerce-store-website/package-lock.json
- ecommerce-store-website/package.json
- ecommerce-store-website/src/base/utils/error-logging.js
- ecommerce-store-website/src/pages/_app.js
- ecommerce-store-website/src/pages/_document.js
This feature implements DataDog into Brand Connector Demo Website.
Changes made include:
- Enabled DataDog to track when ENV is 'development'
- Added testing details to ReadMe for testing in development ENV
- Enable DataDog error tracking for Production ENV by default
> added datadog

- ticket-issuer-url-website/src/App.js
- ticket-issuer-url-website/src/index.js
Logic added to catch errors from re-direct mode to make the error handling consistent across attestation strategies, redirect, tab, iframe.
> added ticket issuer re-direct fix

- hotel-bogota-passive-negotiation-website/src/App.js
Fix is very simple. react app updated tokens list only when 1+ tokens available 
cc @nicktaras
> fix: 🐛 fixed refresh to 0 tokens

- .github/workflows/build-examples.yml
- .github/workflows/deploy-to-gh-pages.yml
- .github/workflows/token-outlet-website.yml
This PR just adds "patch" as an option in the drop-down to select which TKN branch to use in the examples' pipelines.
Solves [TKS-956](https://smarttokenlabs.atlassian.net/browse/TKS-956).
[TKS-956]: https://smarttokenlabs.atlassian.net/browse/TKS-956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TKS-956] Added "patch" branch option

- ecommerce-store-website/package-lock.json
- ecommerce-store-website/package.json
- ecommerce-store-website/src/base/utils/error-logging.js
Update made to the logic used to detect production for BC demo. Where ENV production is used for both Staging and Production Env.
Logic update targets the document origin to ensure its the production website, to activate analytics.
> adjusted the check for when dd should be automatically applied

- ticket-issuer-url-website/package-lock.json
- ticket-issuer-url-website/package.json
- ticket-issuer-url-website/src/App.js
- ticket-issuer-url-website/src/components/Token/Token.css
- ticket-issuer-url-website/src/components/Token/index.js
- token-outlet-website/package-lock.json
- token-outlet-website/package.json
- token-outlet-website/webpack.config.js
Update ticket issuer site to support issuing EAS ticket attestations as well as ASN.1 versions. 
Tickets are identified by devconId-ticketId, tickets already created in ASN format can be reissued in EAS format and imported to replace the ASN version.
> Feature: eas ticket

- typescript-bare-bones-demo/package-lock.json
CICD process run did not automatically update the package lock files of all the examples correctly.
Manually updated this time.
> update versions to 2.7.0

- multiTokenConfig.json
This PR defines a off-chain token config that uses an arbitrary schema. 
Tokens for this issuer config can be generated using this attestation creator link:
https://create.openloyalty.com/#schema=eyJjb25maWciOnsiYWRkcmVzcyI6IjB4QzI2NzlmQkQzN2Q1NDM4OENlNDkzRjFEQjc1MzIwRDIzNmUxODE1ZSIsInZlcnNpb24iOiIwLjI2IiwiY2hhaW5JZCI6MTExNTUxMTF9LCJmaWVsZHMiOlt7Im5hbWUiOiJ0b2tlbklkIiwiZGVzY3JpcHRpb24iOiJUb2tlbiBJRCIsInR5cGUiOiJzdHJpbmciLCJpc0NvbW1pdG1lbnQiOmZhbHNlfSx7Im5hbWUiOiJvd25lck5hbWUiLCJkZXNjcmlwdGlvbiI6Ik5hbWUgb2Ygb3duZXIiLCJ0eXBlIjoic3RyaW5nIiwiaXNDb21taXRtZW50IjpmYWxzZX0seyJuYW1lIjoiY29tbWl0bWVudCIsImRlc2NyaXB0aW9uIjoiVGhlIGVtYWlsIGFkZHJlc3Mgb2YgdGhlIHVzZXIuIFRoaXMgdmFsdWUgaXMgaGlkZGVuIGluIGEgcGVkZXJzZW4gY29tbWl0bWVudCBhbmQgdXNlZCB0byB2ZXJpZnkgb3duZXJzaGlwIiwidHlwZSI6ImJ5dGVzIiwiaXNDb21taXRtZW50 …
> chore: add token config for example arbitrary EAS schema

- ecommerce-store-website/src/ui/components/minter/minter.module.scss
- hotel-bogota-passive-negotiation-website/src/App.js
- hotel-bogota-passive-negotiation-website/src/BookingModal/index.js
Fix to passive flow discount shown in UI once proof is known.
> fix to discount shown for passive flow
